apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: example-resources.mydomain.com
spec:
  group: mydomain.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                size:
                  type: integer
  scope: Namespaced
  names:
    plural: exampleresources
    singular: exampleresource
    kind: ExampleResource
    shortNames:
      - exres

